### ISSUE TITLE
Can this new features be added to the Validator?

### ISSUE THREAD

**Issue by nbaua** [JasonBro/Xam.Plugin.Validators#2]
Hi,

Please consider this as a feature request. :)

This is really Nice implementation, I haven't tried yet, However I can see that it will work well in MVVM world, However I need to know is it possible to apply multiple validations on a single Entry control.

For e.g.

 v:Validation.Validator= "{v:EntryRequired} + {v:NumericRequired }

Also Can this plug-in be extended  further to other controls like EDITOR where I want to restrict the user to enter maximum of 500 characters (Yes I am using Behavior in Xamarin right now, which works great, though without error message) AND at least enter 30 Characters. (Use case - About Yourself on any Profiles page)

Or to more delicate control like DatePicker in XF, where I need to restrict the Date in specific range?
(Use case : No future date allowed for Birth date field OR user must be at least 18 years old for registration.)

Thanks, great work 👍 

N Baua

**Comment by JasonBro** [comment]
Hi N Baua,

Thanks for the email. All the validators are are nicely packaged
behaviours, so you can add multiple validators just by adding them as
behaviours. Have a quick look at the source code to see what I mean. Also,
the validators are easy to extend, so you should be able to create
DatePicker or any other validators.

Let me know if you have a problem and I'll come up with some better
inctructions and some code for you.

Cheers

Jason

**Comment by nbaua** [comment]
Thanks,
Great I will install the plug-in and check.

Meantime would love you to add these in example if you can so everyone could benefit from the same.
If I could finish some of my pending project work early next week would try to work on this and is possible share you the same, you can add it here.

Thanks for your prompt reply. 👍 

N Baua
